CDAP-15813: Vertica export plugin validations.
AntonGensitskiy/vertica-bulk-export pull request #1
Opened 2019-09-11 13:03 UTC by AntonGensitskiy

JIRA: https://issues.cask.co/browse/CDAP-15813
WIKI: https://wiki.cask.co/display/CE/Guidelines+on+Plugin+Validation

In scope of this PR:

- integrated with new validation API

2019-09-11 20:52 UTC, mlozbin-cybervisiontech requested changes

2019-09-11 20:52 UTC, mlozbin-cybervisiontech commented on src/main/java/io/cdap/plugin/db/batch/action/vertica/export/VerticaBulkExportAction.java
> +        failureCollector.addFailure("File path is required.",null)
provide corrective action. For example "File path must be specified"

2019-09-11 20:52 UTC, mlozbin-cybervisiontech commented on src/main/java/io/cdap/plugin/db/batch/action/vertica/export/VerticaBulkExportAction.java
> +        failureCollector.addFailure("Connection string is required.", null)
provide corrective action. For example "File path must be specified"

2019-09-11 20:52 UTC, mlozbin-cybervisiontech commented on src/main/java/io/cdap/plugin/db/batch/action/vertica/export/VerticaBulkExportAction.java
> +          String.format("'%s' is null.", USER),
1. use property name from UI widget, not from constant (in this case just start from uppercase letter)
2. check for empty string (Strings class utility methods)
3. "User is not specified"

2019-09-11 20:52 UTC, mlozbin-cybervisiontech commented on src/main/java/io/cdap/plugin/db/batch/action/vertica/export/VerticaBulkExportAction.java
> +          String.format("'%s' is null.", PASSWORD),
1. use property name from UI widget, not from constant (in this case just start from uppercase letter)
2. check for empty string (Strings class utility methods)
3. "Password is not specified"

2019-09-11 20:52 UTC, mlozbin-cybervisiontech commented on src/main/java/io/cdap/plugin/db/batch/action/vertica/export/VerticaBulkExportAction.java
> +  public static class VerticaExportConfig extends PluginConfig {
1. move this class to upper level (make not inner)
2. class should be immutable
3. add builder

2019-09-11 20:52 UTC, mlozbin-cybervisiontech commented on src/test/java/io/cdap/plugin/db/batch/action/vertice/export/VerticaBulkExportActionConfigTest.java
> +    config.connectionString = null;
use builder, not mutable fields

2019-09-11 20:52 UTC, mlozbin-cybervisiontech commented on src/test/java/io/cdap/plugin/db/batch/action/vertice/export/VerticaBulkExportActionConfigTest.java
> +  public void testValidateConfig() {
this method name does not describe what is tested

2019-09-11 20:52 UTC, mlozbin-cybervisiontech commented on src/test/java/io/cdap/plugin/db/batch/action/vertice/export/VerticaBulkExportActionConfigTest.java
> +    for (int i = 0; i < failureList.size(); i++) {
why don't you use foreach? Why do you need to check that failures were collected in same order as params in paramName list?

2019-09-11 20:52 UTC, mlozbin-cybervisiontech commented on src/test/java/io/cdap/plugin/db/batch/action/vertice/export/VerticaBulkExportActionConfigTest.java
> +                                             int failuresCount) {
in what case failuresCount is not same as paramName.size?

2019-09-12 12:42 UTC, AntonGensitskiy commented on src/main/java/io/cdap/plugin/db/batch/action/vertica/export/VerticaBulkExportAction.java
> +        failureCollector.addFailure("File path is required.",null)
Done.

2019-09-12 12:42 UTC, AntonGensitskiy commented on src/main/java/io/cdap/plugin/db/batch/action/vertica/export/VerticaBulkExportAction.java
> +        failureCollector.addFailure("Connection string is required.", null)
Done.

2019-09-12 12:42 UTC, AntonGensitskiy commented on src/main/java/io/cdap/plugin/db/batch/action/vertica/export/VerticaBulkExportAction.java
> +          String.format("'%s' is null.", USER),
Done.

2019-09-12 12:42 UTC, AntonGensitskiy commented on src/main/java/io/cdap/plugin/db/batch/action/vertica/export/VerticaBulkExportAction.java
> +          String.format("'%s' is null.", PASSWORD),
Done.

2019-09-12 12:42 UTC, AntonGensitskiy commented on src/main/java/io/cdap/plugin/db/batch/action/vertica/export/VerticaBulkExportAction.java
> +  public static class VerticaExportConfig extends PluginConfig {
Done.

2019-09-12 12:42 UTC, AntonGensitskiy commented on src/test/java/io/cdap/plugin/db/batch/action/vertice/export/VerticaBulkExportActionConfigTest.java
> +    config.connectionString = null;
Done.

2019-09-12 12:42 UTC, AntonGensitskiy commented on src/test/java/io/cdap/plugin/db/batch/action/vertice/export/VerticaBulkExportActionConfigTest.java
> +  public void testValidateConfig() {
Name was updated,

2019-09-12 12:42 UTC, AntonGensitskiy commented on src/test/java/io/cdap/plugin/db/batch/action/vertice/export/VerticaBulkExportActionConfigTest.java
> +    for (int i = 0; i < failureList.size(); i++) {
Method was updated.

2019-09-12 12:42 UTC, AntonGensitskiy commented on src/test/java/io/cdap/plugin/db/batch/action/vertice/export/VerticaBulkExportActionConfigTest.java
> +                                             int failuresCount) {
Method was updated.

2019-09-16 09:18 UTC, merged